includeBuild("spring-boot-builder-plugin/spring-boot-build-configuration")
includeBuild("spring-boot-builder-plugin/source/spring-boot-source-java")
includeBuild("spring-boot-builder-plugin/source/spring-boot-source-kotlin")
includeBuild("spring-boot-builder-plugin/openapi/spring-boot-openapi-java")
includeBuild("spring-boot-builder-plugin/openapi/spring-boot-openapi-kotlin")
