includeBuild("spring-boot-builder-plugin/build-configuration")
includeBuild("spring-boot-builder-plugin/source/source-java")
includeBuild("spring-boot-builder-plugin/source/source-kotlin")
includeBuild("spring-boot-builder-plugin/openapi/openapi-java")
includeBuild("spring-boot-builder-plugin/openapi/openapi-kotlin")
