#!/bin/sh

buildTag=$1

if [ -z "$buildTag" ]; then
  buildTag=$(git describe --tags --abbrev=0)
fi

if [ -z "$buildTag" ]; then
  buildTag="1.0.0-SNAPSHOT"
fi

echo "Publishing $buildTag"

if ! ./gradlew \
      build-configuration:assemble build-configuration:publishToMavenLocal \
      java:assemble java:publishToMavenLocal \
      kotlin:assemble kotlin:publishToMavenLocal \
      -Pgroup=com.github.softwareplace --refresh-dependencies -Pversion="$buildTag";
then
  echo "Publish submodules failed $1:$buildTag"
  exit 1
fi

if ! ./gradlew \
      assemble publishToMavenLocal \
      -Pgroup=com.github.softwareplace --refresh-dependencies -Pversion="$buildTag";
then
  echo "Publish springboot failed $1:$buildTag"
  exit 1
fi
