#!/bin/sh

buildTag=$1

if [ -z "$buildTag" ]; then
  buildTag=$(git describe --tags --abbrev=0)
fi

if [ -z "$buildTag" ]; then
  buildTag="1.0.0-SNAPSHOT"
fi

echo "Publishing $buildTag"

if ! ./gradlew clean --parallel \
      versions:assemble versions:publishToMavenLocal --stacktrace \
      utils:assemble utils:publishToMavenLocal --stacktrace \
      build-configuration:assemble build-configuration:publishToMavenLocal --stacktrace \
      java:assemble java:publishToMavenLocal --stacktrace \
      kotlin:assemble kotlin:publishToMavenLocal --stacktrace \
      graalvm:assemble graalvm:publishToMavenLocal --stacktrace \
      -Pgroup=com.github.softwareplace.springboot --refresh-dependencies -Pversion="$buildTag" --stacktrace;
then
  echo "Publish sub-plugins failed $buildTag"
  exit 1
fi

if ! ./gradlew clean --parallel \
      :assemble :publishToMavenLocal --stacktrace \
      -Pgroup=com.github.softwareplace.springboot --refresh-dependencies -Pversion="$buildTag" --stacktrace;
then
  echo "Publish plugins failed for tag $buildTag"
  exit 1
fi

if ! ./gradlew clean --parallel \
      starter:assemble starter:publishToMavenLocal --stacktrace \
      security:assemble security:publishToMavenLocal --stacktrace \
      data-commons:assemble data-commons:publishToMavenLocal --stacktrace \
      -Pgroup=com.github.softwareplace.springboot --refresh-dependencies -Pversion="$buildTag" --stacktrace;
then
  echo "Publish libs failed $buildTag"
  exit 1
fi
