openapi: 3.0.3
info:
  title: Spring boot example api
  description: |-
    Spring sample
  version: 1.0.0
paths:
  /example:
    get:
      tags:
        - Example
      summary: Example swagger
      description: Example swagger
      operationId: exampleBuild
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"

components:
  schemas:
    EnumTest:
      type: string
      enum:
        - TEST
        - TEST_TEST
    BaseResponse:
      type: object
      properties:
        success:
          type: boolean
        timestamp:
          type: integer
          format: int64
        message:
          type: string
        date:
          type: string
          format: date
        dateTime:
          type: string
          format: local-date-time
          example: 2023-06-06T10:42:42.590Z
        time:
          type: string
          format: time
          example: 10:55

#  securitySchemes:
#    petstore_auth:
#      type: oauth2
#      flows:
#        implicit:
#          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
#          scopes:
#            write:pets: modify pets in your account
#            read:pets: read your pets
#    api_key:
#      type: apiKey
#      name: api_key
#      in: header
