#!/bin/sh

gradlePublishLocal() {
  if ! gradle -Pgroup=com.github.softwareplace.plugin -xtest "$1":assemble "$1":publishToMavenLocal;
  then
    echo "Error: Failed to build and publish $1 to Maven Local."
    exit 1
  fi
}

gradlePublishLocal "spring-boot-build-configuration"
gradlePublishLocal "spring-boot-source-kotlin"
gradlePublishLocal "spring-boot-source-java"
gradlePublishLocal "spring-boot-openapi-kotlin"
gradlePublishLocal "spring-boot-openapi-java"
gradlePublishLocal "spring-boot-submodule-source-java"
gradlePublishLocal "spring-boot-submodule-source-kotlin"

echo "All modules built and published successfully."
