#!/bin/sh


gradlePublishLocal() {
  buildTag=$(git describe --tags --abbrev=0)
  rm -rf "$1/build"
  echo "Publishing $1:$buildTag"
  if ! gradle -Pgroup=com.github.softwareplace.plugin "$1":assemble "$1":publishToMavenLocal -Pversion="$buildTag";
  then
    echo "Publish failed $1:$buildTag"
    exit 1
  fi
}

gradlePublishLocal "spring-boot-build-configuration"
gradlePublishLocal "spring-boot-source-kotlin"
gradlePublishLocal "spring-boot-source-java"
gradlePublishLocal "spring-boot-openapi-kotlin"
gradlePublishLocal "spring-boot-openapi-java"
gradlePublishLocal "spring-boot-submodule-source-java"
gradlePublishLocal "spring-boot-submodule-source-kotlin"

echo "All modules built and published successfully."
