name: "Build validation"

on:
  push:
    branches:
      - develop
      - main
      - 'feat/**'
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'

jobs:
  local_publishValidation:
    name: "Local Publish & Test Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - name: Test Validation
        run: make test
