name: "Build validation"

on:
  push:
    branches:
      - develop
      - main
      - 'feat/**'
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'

jobs:
  local_publishValidation:
    name: "Local Publish & Test Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up GraalVM JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
          java-package: 'graalvm' # This installs GraalVM and its tools
      - name: Test Validation
        run: make test
